all:
	g++ TimeKeeper.cpp graph.cpp graphml.cpp -lpthread genfac.cpp genCourse.cpp genstudent.cpp generator.cpp main_2.cpp Semaphore.cpp message_temp.cpp genFriend.cpp -std=c++0x 
	g++ analyser.cpp -o analyser Semaphore.cpp 
	chmod +x ./parta.sh
	chmod +x ./partb.sh
